### ISSUE TITLE
Not installed using composer

### ISSUE THREAD

**Issue by tharun148** [1Forge/php-forex-quotes#1]
I am installing this package using composer but it requires php 5.6.4 but I am having the php 7.0 version

below error occurred 

> Problem 1
>     - Installation request for oneforge/forexquotes 2.0.8 -> satisfiable by oneforge/forexquotes[2.0.8].
>     - oneforge/forexquotes 2.0.8 requires php >=5.6.4 -> your PHP version (7.0.28-0ubuntu0.16.04.1) overridden by "config.platform.php" version (5.6) does not satisfy that requirement.

**Comment by brutus-gr** [comment]
Do you have something like this in your composer.json file?  If so, please remove it and retry.

```
"config": {
    "platform": {
        "php": "5.6"
    }
},
```

**Comment by tharun148** [comment]
I have removed that and now am getting this one

> Problem 1
>     - Conclusion: don't install oneforge/forexquotes 2.0.9
>     - Conclusion: don't install oneforge/forexquotes 2.0.8
>     - Conclusion: don't install oneforge/forexquotes 2.0.7
>     - Conclusion: don't install oneforge/forexquotes 2.0.6
>     - Conclusion: don't install oneforge/forexquotes 2.0.5
>     - Conclusion: don't install oneforge/forexquotes 2.0.4
>     - Conclusion: don't install oneforge/forexquotes 2.0.3
>     - Conclusion: remove guzzlehttp/guzzle 6.3.2
>     - Installation request for oneforge/forexquotes ^2.0 -> satisfiable by oneforge/forexquotes[2.0.0, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9].
>     - Conclusion: don't install guzzlehttp/guzzle 6.3.2
>     - oneforge/forexquotes 2.0.0 requires guzzlehttp/guzzle 6.2.* -> satisfiable by guzzlehttp/guzzle[6.2.0, 6.2.1, 6.2.2, 6.2.3].
>     - Can only install one of: guzzlehttp/guzzle[6.2.0, 6.3.2].
>     - Can only install one of: guzzlehttp/guzzle[6.2.1, 6.3.2].
>     - Can only install one of: guzzlehttp/guzzle[6.2.2, 6.3.2].
>     - Can only install one of: guzzlehttp/guzzle[6.2.3, 6.3.2].
>     - Installation request for guzzlehttp/guzzle (locked at 6.3.2) -> satisfiable by guzzlehttp/guzzle[6.3.2].
>

**Comment by brutus-gr** [comment]
@tharun148 I have upgraded the guzzle requirement to 6.3.*, please upgrade oneforge/forexquotes to 2.0.10 and try again.

**Comment by brutus-gr** [comment]
@tharun148 Are you still having any issues with this?

**Comment by brutus-gr** [comment]
I haven't heard back on this, I'm going to assume you've figured it out.
